const START=126, GOAL=70, STEP=2.5, $=s=>document.querySelector(s);const STORE="unburdened-data-v1";const state=load();
function load(){const base={weights:[],waists:[],photos:[],start:START,goal:GOAL,lastCelebrated:START,reminders:{weight:true,waist:true,photos:true}};try{const a=JSON.parse(localStorage.getItem(STORE)||"null");return a?{...base,...a,reminders:{...base.reminders,...(a.reminders||{})}}:base}catch{return base}}
function save(){localStorage.setItem(STORE,JSON.stringify(state))}function cur(){return state.weights.length?state.weights.at(-1).value:state.start}function lost(){return Math.max(0,state.start-cur())}function rem(){return Math.max(0,cur()-state.goal)}function fmt(n){return Number(n).toFixed(Number(n)%1?1:0)}function today(){return new Date().toISOString().slice(0,10)}
function cps(){let a=[126,125],x=122.5;while(x>=70){a.push(x);x-=2.5}return [...new Set(a)].sort((a,b)=>b-a)}function next(){return cps().find(x=>x<cur())??GOAL}function overall(){return Math.min(100,Math.max(0,lost()/(state.start-state.goal)*100))}
function navActive(v){document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v))}function go(v){navActive(v);({home,log,progress,milestones,more}[v]||home)();scrollTo(0,0)}document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.v));
function pageHead(title,back=false){return `<div class="head">${back?`<button class="back" aria-label="Back">‹</button>`:''}<h1>${title}</h1></div>`}function wireBack(){const b=$('.back');if(b)b.onclick=()=>go('more')}
function trailSteps(w){const all=cps().filter(x=>x<w);return all.slice(0,6)}
function home(){const w=cur(),n=next(),steps=trailSteps(w);const hi=cps().filter(x=>x>=w).at(-1)??START;const pct=Math.max(0,Math.min(100,(hi-w)/Math.max(.1,hi-n)*100));const labels=[...steps];while(labels.length<6)labels.push('');$('#view').innerHTML=`<section class="home-page">
<div class="home-brand"><div><strong>Unburdened</strong><small>Small steps. Big changes.</small></div><button class="home-settings" aria-label="Settings">⚙</button></div>
<div class="approved-art"><img src="assets/journey-production.png?v=19" alt="Illustrated mountain journey with a backpacked hiker, walking stick and milestone trail" onerror="this.onerror=null;this.src='journey-production.png?v=19'">
<div class="trail-label current-trail"><strong>${fmt(w)}</strong><small>YOU ARE HERE</small></div>
${labels.map((x,i)=>x!==''?`<div class="trail-label step-label step-${i+1}">${fmt(x)}</div>`:'').join('')}
</div>
<div class="home-body"><div class="card mission"><div class="mission-label">Current Mission</div><div class="route">${fmt(w)} kg → ${fmt(n)} kg</div><div class="progressbar"><i style="width:${pct}%"></i></div><div class="split muted mini"><span>${fmt(lost())} kg down</span><span>${fmt(Math.max(0,w-n))} kg to next step</span></div></div><div class="grid3"><div class="card stat"><strong>${fmt(w)}</strong><small>Current kg</small></div><div class="card stat"><strong>${fmt(lost())}</strong><small>Total lost</small></div><div class="card stat"><strong>${fmt(rem())}</strong><small>To goal</small></div></div></div></section>`;$('.home-settings').onclick=settingsPage}
function log(){$('#view').innerHTML=`<section class="screen log-screen">${pageHead('Log Weight')}<div class="scale" aria-hidden="true"></div><div class="card form compact-form"><div class="two"><label>Date<input id="date" type="date" value="${today()}"></label><label>Weight (kg)<input id="weight" type="number" step=".1" inputmode="decimal" placeholder="${fmt(cur())}"></label></div><div class="helper">✓ Same conditions each week makes the trend more useful.</div><label>Waist (cm) <span>— optional, every 2 weeks</span><input id="waist" type="number" step=".1" inputmode="decimal" placeholder="e.g. 110"></label><label>Notes <span>— optional</span><textarea id="notes" placeholder="Anything worth remembering?"></textarea></label><button id="saveLog" class="btn">Save Update</button></div></section>`;$('#saveLog').onclick=()=>{const v=parseFloat($('#weight').value),wa=parseFloat($('#waist').value),d=$('#date').value,notes=$('#notes').value.trim();if(!Number.isNaN(v)){state.weights.push({date:d,value:v,notes});checkCelebration(v)}if(!Number.isNaN(wa))state.waists.push({date:d,value:wa});save();go('home')}}
function progress(){$('#view').innerHTML=`<section class="screen">${pageHead('Current Progress')}<div class="card center"><div class="big">${fmt(cur())} kg</div><h2>${fmt(lost())} kg down</h2><p class="muted">${fmt(rem())} kg to go</p><div class="progressbar"><i style="width:${overall()}%"></i></div><div class="split muted mini"><span>${START} kg Start</span><span>${GOAL} kg Goal</span></div></div><div class="card soft center"><strong>Next Checkpoint</strong><div class="checkpoint">${fmt(next())} kg</div><span class="muted">${fmt(Math.max(0,cur()-next()))} kg to go</span></div>${chart()}${waistSummary()}</section>`}
function chart(){const v=state.weights.slice(-12);if(v.length<2)return `<div class="card"><h2>Weight trend</h2><div class="chart empty">Your trend appears after two weigh-ins.<br>One reading never tells the whole story.</div></div>`;const min=Math.min(...v.map(x=>x.value)),max=Math.max(...v.map(x=>x.value)),pad=Math.max(1,(max-min)*.2),lo=min-pad,hi=max+pad,pts=v.map((x,i)=>`${(i/(v.length-1))*100},${95-((x.value-lo)/(hi-lo))*88}`).join(' ');return `<div class="card"><h2>Weight trend</h2><div class="chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${pts}" fill="none" stroke="#25a879" stroke-width="2.5" vector-effect="non-scaling-stroke"/></svg></div></div>`}
function waistSummary(){if(!state.waists.length)return `<div class="card"><h2>Waist</h2><p class="muted">No waist measurements yet.</p></div>`;const a=state.waists[0].value,b=state.waists.at(-1).value;return `<div class="card"><h2>Waist</h2><div class="split"><strong>${fmt(b)} cm</strong><span class="muted">${fmt(a-b)} cm change</span></div></div>`}
function milestones(){$('#view').innerHTML=`<section class="screen">${pageHead('Milestones')}<div id="milestoneList"></div></section>`;renderMilestones()}
function renderMilestones(){const arr=cps(),w=cur(),majorSet=new Set([120,110,100,90,80]);$('#milestoneList').innerHTML=`<div class="card timeline">${arr.map(x=>{const isMajor=majorSet.has(x),isGoal=x===70,isCurrent=next()===x,isDone=w<=x;return `<div class="mile ${isDone?'done':''} ${isCurrent?'current':''} ${isMajor?'major-mile':''} ${isGoal?'goal-mile':''}"><span class="mile-marker">${isGoal?'🏆':isMajor?'⚑':''}</span><strong>${fmt(x)} kg</strong>${isMajor?'<em>Major Milestone</em>':isGoal?'<em>Goal</em>':''}<small>${x===126?'Starting point':isGoal?'Goal':isDone?`${fmt(START-x)} kg lost`:`${fmt(w-x)} kg to go`}</small></div>`}).join('')}</div>`}
function more(){$('#view').innerHTML=`<section class="screen">${pageHead('More')}<div class="card identity"><img src="assets/unburdened-logo.png" alt="Unburdened"><div><strong>Unburdened</strong><span>Less weight. More life.</span></div></div><button class="menu-card" id="photosBtn"><span>▧</span><div><strong>Progress Photos</strong><small>Front • side • back every 4 weeks</small></div><b>›</b></button><button class="menu-card" id="settingsBtn"><span>⚙</span><div><strong>Settings</strong><small>Goals and reminders</small></div><b>›</b></button><button class="menu-card" id="dataBtn"><span>⇩</span><div><strong>Your Data</strong><small>Export or restore a backup</small></div><b>›</b></button></section>`;$('#photosBtn').onclick=photosPage;$('#settingsBtn').onclick=settingsPage;$('#dataBtn').onclick=dataPage}
function photosPage(){navActive('more');$('#view').innerHTML=`<section class="screen">${pageHead('Progress Photos',true)}<div class="card photo-intro"><strong>Front • side • back</strong><p class="muted">About every 4 weeks, with similar lighting and distance.</p><button id="addPhotos" class="btn">+ Add Photos</button></div><div>${photos()}</div></section>`;wireBack();$('#addPhotos').onclick=()=>$('#photoPicker').click()}
function photos(){if(!state.photos.length)return `<div class="card empty-state"><strong>No progress photos yet</strong><p class="muted">Your first set will appear here.</p></div>`;return state.photos.slice().reverse().map(p=>`<div class="card"><strong>${new Date(p.date+'T12:00').toLocaleDateString(undefined,{month:'short',year:'numeric'})}</strong><div class="photo-grid">${p.images.map((x,i)=>`<figure><img src="${x}"><figcaption>${['Front','Side','Back'][i]||''}</figcaption></figure>`).join('')}</div></div>`).join('')}
function settingsPage(){navActive('more');$('#view').innerHTML=`<section class="screen">${pageHead('Settings',true)}<div class="card"><h2>My Goals</h2><div class="row"><span>Starting weight</span><strong>${START.toFixed(1)} kg</strong></div><div class="row"><span>Ultimate goal</span><strong>${GOAL.toFixed(1)} kg</strong></div><div class="row"><span>Checkpoint size</span><strong>${STEP} kg</strong></div></div><div class="card"><h2>Reminders</h2>${toggle('weight','Weekly weigh-in','Once each week')}${toggle('waist','Waist measurement','Every 2 weeks')}${toggle('photos','Progress photos','Every 4 weeks')}</div></section>`;wireBack();document.querySelectorAll('[data-r]').forEach(x=>x.onchange=e=>{state.reminders[e.target.dataset.r]=e.target.checked;save()})}
function toggle(id,a,b){return `<label class="toggle-row"><div><strong>${a}</strong><small>${b}</small></div><input data-r="${id}" type="checkbox" ${state.reminders[id]?'checked':''}><i></i></label>`}
function dataPage(){navActive('more');$('#view').innerHTML=`<section class="screen">${pageHead('Your Data',true)}<div class="card"><h2>Backup</h2><p class="muted">Saved on this device. Export before clearing browser data or changing devices.</p><div class="backup"><button id="export" class="btn light">Export</button><button id="importBtn" class="btn light">Import</button></div><input id="importFile" type="file" accept="application/json" hidden></div></section>`;wireBack();$('#export').onclick=exportSave;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=importSave}
$('#photoPicker').onchange=async e=>{const f=[...e.target.files].slice(0,3);if(!f.length)return;const images=await Promise.all(f.map(resize));state.photos.push({date:today(),images});save();photosPage();e.target.value=''};function resize(f){return new Promise(r=>{const fr=new FileReader();fr.onload=()=>{const im=new Image;im.onload=()=>{const c=document.createElement('canvas'),s=Math.min(1,900/im.width);c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);r(c.toDataURL('image/jpeg',.82))};im.src=fr.result};fr.readAsDataURL(f)})}
function checkCelebration(v){const h=cps().filter(x=>v<=x&&state.lastCelebrated>x);if(!h.length)return;const hit=Math.min(...h);state.lastCelebrated=hit;save();setTimeout(()=>celebrate(hit),50)}function celebrate(hit){const o=$('#celebrate');o.classList.remove('hidden');o.innerHTML=`<div class="celebrate-box"><div class="confetti">◆ ✦ ● ✦ ◆</div><h1>Checkpoint Reached!</h1><div class="flag-rock">🚩</div><div class="kg">${fmt(hit)} kg</div><h2>${fmt(START-hit)} kg down</h2><p>${fmt(hit-GOAL)} kg to go</p><button class="btn" id="closeCelebration">Continue</button></div>`;$('#closeCelebration').onclick=()=>o.classList.add('hidden')}
function exportSave(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`unburdened-save-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}function importSave(e){const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{try{Object.assign(state,JSON.parse(r.result));save();dataPage();alert('Backup restored.')}catch{alert('That save file could not be read.')}};r.readAsText(f)}
home();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');